import { chromium } from 'playwright';
const S = process.argv[2];
const b = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const m = await b.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 }); const errs = [];
m.on('pageerror', e => errs.push(e.message));
await m.goto('file:///home/user/GG/dist/arcade.html'); await m.waitForTimeout(1500); await m.tap('#start'); await m.waitForTimeout(5000);
await m.evaluate(() => { const A = window.__arcade; A.earn(5000); A.build(1,0,'point'); A.build(0,1,'point'); A.act('up',1,0); A.build(-1,0,'line'); A.build(1,-1,'point'); A.setMode(null); });
await m.waitForTimeout(6000); await m.screenshot({ path: `${S}/8-mob-a.png` });
await m.evaluate(() => window.__arcade.openCard(1, 0)); await m.waitForTimeout(5000); await m.screenshot({ path: `${S}/8-mob-b.png` });
console.log('errors', errs, await m.textContent('#rate')); await b.close();
